### ISSUE TITLE
task4.md

### ISSUE THREAD

**Issue by 1155108884** [csci3250-2019/project-team-h#12]
I will do task4.

**Comment by CohenQU** [comment]
After you finish task4.md, could you send me a notification, then I will do task5. Just @CohenQU , then I will know.

**Comment by HoTszYanAnn** [comment]
Is this task finished? Can I assign myself into this task? @1155108884

**Comment by 1155108884** [comment]
I have already finished task4. @CohenQU @HoTszYanAnn

**Comment by Abdalla981** [comment]
Did someone review it?

**Comment by CohenQU** [comment]
I will check this task.

**Comment by CohenQU** [comment]
@1155108884 Did you got the GitHub shield for Travis CI, which is the third part of issue 4? Cause I am not clear which part of code is offered by the repo, and which is written by yourself. Don't worry, just for double checking this issue.

**Comment by 1155108884** [comment]
Yes, I did.

**Comment by CohenQU** [comment]
Well done.
