### ISSUE TITLE
task3.md

### ISSUE THREAD

**Issue by mcchow8** [csci3250-2019/project-team-h#15]
The Project board of task3 is created. Please help me to check it whether it is correct

**Comment by CohenQU** [comment]
You need to assign another team member to check this part. 
Click Assignees->Find someone with no more than two reviews->Add

**Comment by Abdalla981** [comment]
Maybe you can add me to review it, @Abdalla981

**Comment by CohenQU** [comment]
@Abdalla981 I have assigned you to review this issue.

**Comment by Abdalla981** [comment]
Well this task seems okay but I am wondering why it doesn't work properly? We have 6 pull requests but they are not under In progress. Also we successfully merged more than 30 times but they are not under "Done"

**Comment by Abdalla981** [comment]
Anyone knows how to fix it? or should I just close it as it is

**Comment by CohenQU** [comment]
@Abdalla981 Let me check it, wait me a moment.

**Comment by Abdalla981** [comment]
Well I think it's working now. May I know what did you change @CohenQU

**Comment by Abdalla981** [comment]
I think we need to uncheck that when a pull request is reviewed, it will be added to In progress.

**Comment by CohenQU** [comment]
@Abdalla981 I think it works now. For making project board record the "Pull request" and "Issues", we should assign it to the corresponding project. As it shown in this picture.  
<img width="715" alt="picture" src="https://user-images.githubusercontent.com/39026248/56489374-19e99300-6514-11e9-8d15-35b58eb95830.png">

So, when you create a new issue or ask for a new pull request, remember to assign it to the corresponding project, then the project board will catch these changes.

**Comment by Abdalla981** [comment]
Okay great.

**Comment by Abdalla981** [comment]
Should we uncheck that when a pull request is reviewed, it will be added to In progress. cause it should be in Done instead?

**Comment by Abdalla981** [comment]
@CohenQU ?

**Comment by CohenQU** [comment]
@Abdalla981 Sorry, I was moving these tags to their correct column. How about checking the project board one more time.

**Comment by Abdalla981** [comment]
Yep, everything is great now

**Comment by Abdalla981** [comment]
This task is done and reviewed correctly. It will be closed now.

**Comment by CohenQU** [comment]
Cause there are 35 pull request has merged without assignment of project, when I assign a project tag to each of them, the project board will treat this operation as "create a new pull request", even though it has been merged, so I need to move it from "In progress" to "Done" one by one. 
Also I have checked the automation management, you review these pull request, it won't be transformed to "In Progress" column.

**Comment by Abdalla981** [comment]
okay great, I think the board is working now as it should be.
