### ISSUE TITLE
task5.md

### ISSUE THREAD

**Issue by CohenQU** [csci3250-2019/project-team-h#18]

**Comment by CohenQU** [comment]
@chuckjee 
As shown in the [task5.md](https://github.com/csci3250-2019/project-team-h/blob/master/issues/task5.md), my question is which file should I edit to add the corresponding link.

**Comment by HoTszYanAnn** [comment]
Sorry for asking a silly question, each task is for one people only? and all the tasks are chosen?

**Comment by mchan21133** [comment]
I also have the same question.

**Comment by Lokts0311** [comment]
I also have the same question.Is there any task left?

**Comment by HoTszYanAnn** [comment]
How about this task? Is this task finished? Can I assign myself here? @CohenQU

**Comment by Abdalla981** [comment]
I also have the same questions, is there any tasks left?

**Comment by Abdalla981** [comment]
Is this task finished? @CohenQU

**Comment by HoTszYanAnn** [comment]
@CohenQU @Abdalla981 I've just finished the Task5, edit and add our Team H link into csci3250-2019.github.io file.

**Comment by CohenQU** [comment]
I think 5 of us should finish this task, and other students should check these task

**Comment by HoTszYanAnn** [comment]
@Lokts0311 I find that you also request a review to add a link in that readme, but you do not have tagged the professor and assign yourself here. Can you remove your request at that page?

**Comment by HoTszYanAnn** [comment]
@CohenQU Maybe we need to wait until the professor approves our change on that file.

**Comment by CohenQU** [comment]
@HoTszYanAnn  If you ask for "pull request" to the "master branch", we need to wait for the professor's approval.

**Comment by HoTszYanAnn** [comment]
@CohenQU yes, I have asked for the "pull request" and now is waiting for the professor's approval.

**Comment by CohenQU** [comment]
@HoTszYanAnn Got it. I'm still checking #task4, later I will check this task.

**Comment by HoTszYanAnn** [comment]
@CohenQU great, Thank you very much :)

**Comment by Lokts0311** [comment]
@HoTszYanAnn  ok I have removed

**Comment by CohenQU** [comment]
@HoTszYanAnn Can you assigned some other students to help you check this issue? After done the "pull request"

**Comment by HoTszYanAnn** [comment]
@Lokts0311 Sorry, and thanks :)

**Comment by HoTszYanAnn** [comment]
@CohenQU ok, maybe @Lokts0311 help me check this issue?

**Comment by HoTszYanAnn** [comment]
but the "pull request" haven't done now :p, I will tag you after I find that is ok.

**Comment by Lokts0311** [comment]
@HoTszYanAnn OK. Thank you.

**Comment by HoTszYanAnn** [comment]
@Lokts0311 it’s done！ Please help me check this issue and close it. Thank you very much. (≧∇≦)b
