### ISSUE TITLE
Further task

### ISSUE THREAD

**Issue by CohenQU** [csci3250-2019/project-team-h#41]
Cause We have closed task#2, but we still can enhance the page outlook by changing the theme, or preparing new CSS!
Here is our website: https://csci3250-2019.github.io/project-team-h/
please read about include_relative on this page: https://jekyllrb.com/docs/includes/

**Comment by jzzhang8** [comment]
The deadline is 30 minutes later. Do we need to close this issue before that?

**Comment by HoTszYanAnn** [comment]
I think we should close it before the deadline. Right?

**Comment by HoTszYanAnn** [comment]
Maybe someone who hasn't fulfilled to do two reviews or issues do it before the deadline, please. :)

**Comment by jzzhang8** [comment]
Only 7 minutes left, please be quick

**Comment by HoTszYanAnn** [comment]
@slcssamy maybe you closed it quick, please. I think that you haven't fulfilled the requirement :)

**Comment by slcssamy** [comment]
Okay... im done. Thx

「HoTszYanAnn <notifications@github.com>」在 2019年4月24日 週三，下午11:55 寫道：

**Comment by jzzhang8** [comment]
ok

**Comment by jzzhang8** [comment]
all finished, thank you everyone
