### ISSUE TITLE
A reminder (one basic task that we all have to do)

### ISSUE THREAD

**Issue by mchan21133** [csci3250-2019/project-team-h#47]
I checked the email from the professor and found that there is one basic task that we have to do. (the highlighted one)

(Email from professor)
Some of you got confused by the long task list. You can understand it this way:

Basic tasks:

* create the 1155xxxxxx.md file in _stu for your info
* add a card of yourself in the project board
* check readme.md to include your 1155xxxxxx.md file into it
* **move your card of yourself in the project board to “Done”**

Shared tasks (you may pick one to finish):

* any one of the 5 items in the issues folder
-> add it to “issues”
-** check, comment and close** an open issue that’s not by you
* review and merge a pull request that’s not by you
There are some constraints mentioned in tasks.md so please pay attention to them.
Cheers!

I also found the related description under tasks.md.

**9. When you consider all your individual work done, please go to the Projects board and move your intro (step 2 above) to Done**

I saw that we all finished the **individual works**  (we may even finished all the group works!), but no one moved his/her card in the project board to "done". Therefore, this is just to remind you that **do not forget to move your intro to done**

Thank you.

**Comment by Abdalla981** [comment]
Thank you for the reminder.

**Comment by Abdalla981** [comment]
I think it's safe to do it now since we finished everything

**Comment by JackWong0303** [comment]
Maybe a silly question... How to add a card to the project board? I couldn't find the button to add the new card.

**Comment by jzzhang8** [comment]
Thank you for your reminder.

**Comment by CohenQU** [comment]
@JackWong0303 https://github.com/csci3250-2019/project-team-h/projects/2 You will find "+" on the top of each column, then type your information in that tag, you will create a new card.

**Comment by JackWong0303** [comment]
@CohenQU The point is I cant see the "+". This is weird.

**Comment by HoTszYanAnn** [comment]
May you capture that page and post it here？ @JackWong0303

**Comment by JackWong0303** [comment]
![image](https://user-images.githubusercontent.com/48310199/56558440-59c28000-65d1-11e9-9101-d4019f90470b.png)

It is like that.

**Comment by HoTszYanAnn** [comment]
You can try to press the menu button and see if there any "add card" button?

**Comment by JackWong0303** [comment]
![image](https://user-images.githubusercontent.com/48310199/56558630-e79e6b00-65d1-11e9-8048-7a583d249329.png)

No, it doesn't.

**Comment by HoTszYanAnn** [comment]
Or maybe you write down your content here, and I help you to create a new card.

**Comment by JackWong0303** [comment]
@HoTszYanAnn 
"Hello, I am Jack, a year 2 CS student." Thank you so much.

**Comment by HoTszYanAnn** [comment]
Are you a member of this team h?

**Comment by HoTszYanAnn** [comment]
It seems that you haven't joined in team h

**Comment by JackWong0303** [comment]
@HoTszYanAnn  ahhhh... that's why. I've rechecked the email and joined in just now. Thank you so much for reminding me. Appreciate that.

**Comment by HoTszYanAnn** [comment]
That's great ^_^

**Comment by sinyiwsy** [comment]
Oh Thank your reminder.

**Comment by Abdalla981** [comment]
Btw guys, you can just drag the card from "To Do" to "Done".

**Comment by mchan21133** [comment]
I can only find 12 self-introduction cards (0 in "To do", 12 in "Done") but we have 16 people. Please do not forget to create your card and drag it to "Done". Thank you.
