### ISSUE TITLE
task2.md

### ISSUE THREAD

**Issue by fungking07** [csci3250-2019/project-team-h#8]
You are going to update this website: https://csci3250-2019.github.io/project-team-h/

Please read about include_relative on this page: https://jekyllrb.com/docs/includes/

Here are your tasks:

- [x] Edit readme.md
- [x] Under Contributors, use include_relative to include your own md file under the folder _stu
- [x] At the bottom of the page, include the last updated time using site.time (HOW?)

(Feel free to enhance the page outlook by changing the theme, or preparing new CSS!)

**Comment by sinyiwsy** [comment]
ADD OIL :1st_place_medal:

**Comment by Abdalla981** [comment]
Is this task finished?

**Comment by Abdalla981** [comment]
If it is, did someone review it?

**Comment by CohenQU** [comment]
There is no problem with this issue. Let's close it.

**Comment by Abdalla981** [comment]
I will change the label to Done then
